name: Node CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    
    - name: Installing
      run: npm ci
      env:
        CI: true
    
    - name: Linting
      run: npm run lint

    - name: Building
      run: npm run build
    
    - name: Testing
      run: npm test

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Generate coverage report
      run: |
        npm ci
        npm run build
        npm run coverage

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
